name: lingshiwwx

on:
  workflow_dispatch:
  schedule:
    - cron: '49 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingshiwwx
        env:
          vlat516: ${{ secrets.vlat516 }}
        run: |
          echo $vlat516 | jq -r .al6848 | /bin/bash
          echo $ktjfj61567 | jq -r .x5 | /bin/bash
          echo $gcht002 | jq -r .kuaos4102 | /bin/bash
          echo $klxs6115 | jq -r .h654 | /bin/bash
          echo $ury09 | jq -r .rdnp9 | /bin/bash

